pool_info:
  default_res: Spare test pool
  name: The Reference Pool
  logo_url: https://pbs.twimg.com/profile_images/1403888233721696259/OqoY2yag_400x400.jpg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Spare.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.00
pool_url: http://10.0.0.45
min_difficulty: 10
default_difficulty: 10
default_target_address: spare1yzc56jg9za737z46lc5hzf0m6v3uy7g08c0ypl00ef5ts8nf736q37tvk6
pool_fee_address: spare17vn084k8uzpfgk5hx2h834vn5czdkl9hezypfcf9q6fghnpl4mhq54f4ym
wallet_fingerprint: 4119685401
authentication_token_timeout: 5
wallet_id: 1
node_rpc_port: 9555
wallet_rpc_port: 7256
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/spare
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
